[package]
name = "rusting"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = { version = "1.0.17", features = [
    "zlib-rs",
], default-features = false }
regex = "1.10"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
indicatif = { version = "*" }
rustc-hash = "2.1.1"
rkyv = "0.8.11"
memmap2 = "0.9.7"

# in pagelinks_parser.rs
atoi = "2.0.0"
